default:
  image: python:3.10-slim
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate 

stages:
  - test
  - lint

Test:
  stage: test
  script:
    - poetry run uvicorn src.app.main:app --port 24023 & poetry run pytest
  
Linter:
  stage: lint
  script:
    - poetry run flake8 .
