default:
  image: python:3.10-slim
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate 

stages:
  - test
  - lint

Test:
  stage: test
  services:
    - postgres
  variables:
    DB_NAME: shift
    DB_LOGIN: postgres
    DB_PASSWORD: 1234
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - poetry run uvicorn src.app.main:app --port 24023 & poetry run pytest
  
Linter:
  stage: lint
  script:
    - poetry run flake8 .
