apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres.test.svc.cluster.local
  POSTGRES_USER: shift-postgres-test
  POSTGRES_PASSWORD: shift-postgres-test
